// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "flowforge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	workflow "flowforge/internal/workflow"
)

// MockWorkflowRepository is an autogenerated mock type for the WorkflowRepository type
type MockWorkflowRepository struct {
	mock.Mock
}

type MockWorkflowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowRepository) EXPECT() *MockWorkflowRepository_Expecter {
	return &MockWorkflowRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, wf
func (_m *MockWorkflowRepository) Create(ctx context.Context, wf *domain.Workflow) error {
	ret := _m.Called(ctx, wf)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Workflow) error); ok {
		r0 = rf(ctx, wf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflowRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWorkflowRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - wf *domain.Workflow
func (_e *MockWorkflowRepository_Expecter) Create(ctx interface{}, wf interface{}) *MockWorkflowRepository_Create_Call {
	return &MockWorkflowRepository_Create_Call{Call: _e.mock.On("Create", ctx, wf)}
}

func (_c *MockWorkflowRepository_Create_Call) Run(run func(ctx context.Context, wf *domain.Workflow)) *MockWorkflowRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Workflow))
	})
	return _c
}

func (_c *MockWorkflowRepository_Create_Call) Return(_a0 error) *MockWorkflowRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflowRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Workflow) error) *MockWorkflowRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, tenantID, id
func (_m *MockWorkflowRepository) FindByID(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Workflow, error) {
	ret := _m.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Workflow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Workflow, error)); ok {
		return rf(ctx, tenantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Workflow); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockWorkflowRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
func (_e *MockWorkflowRepository_Expecter) FindByID(ctx interface{}, tenantID interface{}, id interface{}) *MockWorkflowRepository_FindByID_Call {
	return &MockWorkflowRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, tenantID, id)}
}

func (_c *MockWorkflowRepository_FindByID_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID)) *MockWorkflowRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkflowRepository_FindByID_Call) Return(_a0 *domain.Workflow, _a1 error) *MockWorkflowRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Workflow, error)) *MockWorkflowRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDForUpdate provides a mock function with given fields: ctx, tenantID, id
func (_m *MockWorkflowRepository) FindByIDForUpdate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Workflow, error) {
	ret := _m.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDForUpdate")
	}

	var r0 *domain.Workflow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Workflow, error)); ok {
		return rf(ctx, tenantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Workflow); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowRepository_FindByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDForUpdate'
type MockWorkflowRepository_FindByIDForUpdate_Call struct {
	*mock.Call
}

// FindByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
func (_e *MockWorkflowRepository_Expecter) FindByIDForUpdate(ctx interface{}, tenantID interface{}, id interface{}) *MockWorkflowRepository_FindByIDForUpdate_Call {
	return &MockWorkflowRepository_FindByIDForUpdate_Call{Call: _e.mock.On("FindByIDForUpdate", ctx, tenantID, id)}
}

func (_c *MockWorkflowRepository_FindByIDForUpdate_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID)) *MockWorkflowRepository_FindByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkflowRepository_FindByIDForUpdate_Call) Return(_a0 *domain.Workflow, _a1 error) *MockWorkflowRepository_FindByIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowRepository_FindByIDForUpdate_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Workflow, error)) *MockWorkflowRepository_FindByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, f
func (_m *MockWorkflowRepository) List(ctx context.Context, f workflow.ListWorkflowsFilter) ([]*domain.Workflow, int64, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Workflow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, workflow.ListWorkflowsFilter) ([]*domain.Workflow, int64, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workflow.ListWorkflowsFilter) []*domain.Workflow); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workflow.ListWorkflowsFilter) int64); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, workflow.ListWorkflowsFilter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWorkflowRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkflowRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - f workflow.ListWorkflowsFilter
func (_e *MockWorkflowRepository_Expecter) List(ctx interface{}, f interface{}) *MockWorkflowRepository_List_Call {
	return &MockWorkflowRepository_List_Call{Call: _e.mock.On("List", ctx, f)}
}

func (_c *MockWorkflowRepository_List_Call) Run(run func(ctx context.Context, f workflow.ListWorkflowsFilter)) *MockWorkflowRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workflow.ListWorkflowsFilter))
	})
	return _c
}

func (_c *MockWorkflowRepository_List_Call) Return(_a0 []*domain.Workflow, _a1 int64, _a2 error) *MockWorkflowRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockWorkflowRepository_List_Call) RunAndReturn(run func(context.Context, workflow.ListWorkflowsFilter) ([]*domain.Workflow, int64, error)) *MockWorkflowRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetCurrentVersion provides a mock function with given fields: ctx, tenantID, workflowID, versionID, versionNumber, expectedRowVersion
func (_m *MockWorkflowRepository) SetCurrentVersion(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID, versionID uuid.UUID, versionNumber int, expectedRowVersion int) error {
	ret := _m.Called(ctx, tenantID, workflowID, versionID, versionNumber, expectedRowVersion)

	if len(ret) == 0 {
		panic("no return value specified for SetCurrentVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int, int) error); ok {
		r0 = rf(ctx, tenantID, workflowID, versionID, versionNumber, expectedRowVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflowRepository_SetCurrentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCurrentVersion'
type MockWorkflowRepository_SetCurrentVersion_Call struct {
	*mock.Call
}

// SetCurrentVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - workflowID uuid.UUID
//   - versionID uuid.UUID
//   - versionNumber int
//   - expectedRowVersion int
func (_e *MockWorkflowRepository_Expecter) SetCurrentVersion(ctx interface{}, tenantID interface{}, workflowID interface{}, versionID interface{}, versionNumber interface{}, expectedRowVersion interface{}) *MockWorkflowRepository_SetCurrentVersion_Call {
	return &MockWorkflowRepository_SetCurrentVersion_Call{Call: _e.mock.On("SetCurrentVersion", ctx, tenantID, workflowID, versionID, versionNumber, expectedRowVersion)}
}

func (_c *MockWorkflowRepository_SetCurrentVersion_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID, versionID uuid.UUID, versionNumber int, expectedRowVersion int)) *MockWorkflowRepository_SetCurrentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockWorkflowRepository_SetCurrentVersion_Call) Return(_a0 error) *MockWorkflowRepository_SetCurrentVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflowRepository_SetCurrentVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int, int) error) *MockWorkflowRepository_SetCurrentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// TouchRowVersion provides a mock function with given fields: ctx, tenantID, id, expectedRowVersion
func (_m *MockWorkflowRepository) TouchRowVersion(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, expectedRowVersion int) error {
	ret := _m.Called(ctx, tenantID, id, expectedRowVersion)

	if len(ret) == 0 {
		panic("no return value specified for TouchRowVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, tenantID, id, expectedRowVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflowRepository_TouchRowVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchRowVersion'
type MockWorkflowRepository_TouchRowVersion_Call struct {
	*mock.Call
}

// TouchRowVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
//   - expectedRowVersion int
func (_e *MockWorkflowRepository_Expecter) TouchRowVersion(ctx interface{}, tenantID interface{}, id interface{}, expectedRowVersion interface{}) *MockWorkflowRepository_TouchRowVersion_Call {
	return &MockWorkflowRepository_TouchRowVersion_Call{Call: _e.mock.On("TouchRowVersion", ctx, tenantID, id, expectedRowVersion)}
}

func (_c *MockWorkflowRepository_TouchRowVersion_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, expectedRowVersion int)) *MockWorkflowRepository_TouchRowVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MockWorkflowRepository_TouchRowVersion_Call) Return(_a0 error) *MockWorkflowRepository_TouchRowVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflowRepository_TouchRowVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int) error) *MockWorkflowRepository_TouchRowVersion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetadata provides a mock function with given fields: ctx, wf, expectedRowVersion
func (_m *MockWorkflowRepository) UpdateMetadata(ctx context.Context, wf *domain.Workflow, expectedRowVersion int) error {
	ret := _m.Called(ctx, wf, expectedRowVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetadata")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Workflow, int) error); ok {
		r0 = rf(ctx, wf, expectedRowVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflowRepository_UpdateMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetadata'
type MockWorkflowRepository_UpdateMetadata_Call struct {
	*mock.Call
}

// UpdateMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - wf *domain.Workflow
//   - expectedRowVersion int
func (_e *MockWorkflowRepository_Expecter) UpdateMetadata(ctx interface{}, wf interface{}, expectedRowVersion interface{}) *MockWorkflowRepository_UpdateMetadata_Call {
	return &MockWorkflowRepository_UpdateMetadata_Call{Call: _e.mock.On("UpdateMetadata", ctx, wf, expectedRowVersion)}
}

func (_c *MockWorkflowRepository_UpdateMetadata_Call) Run(run func(ctx context.Context, wf *domain.Workflow, expectedRowVersion int)) *MockWorkflowRepository_UpdateMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Workflow), args[2].(int))
	})
	return _c
}

func (_c *MockWorkflowRepository_UpdateMetadata_Call) Return(_a0 error) *MockWorkflowRepository_UpdateMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflowRepository_UpdateMetadata_Call) RunAndReturn(run func(context.Context, *domain.Workflow, int) error) *MockWorkflowRepository_UpdateMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, tenantID, id, status, expectedRowVersion
func (_m *MockWorkflowRepository) UpdateStatus(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, status string, expectedRowVersion int) error {
	ret := _m.Called(ctx, tenantID, id, status, expectedRowVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int) error); ok {
		r0 = rf(ctx, tenantID, id, status, expectedRowVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflowRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockWorkflowRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
//   - status string
//   - expectedRowVersion int
func (_e *MockWorkflowRepository_Expecter) UpdateStatus(ctx interface{}, tenantID interface{}, id interface{}, status interface{}, expectedRowVersion interface{}) *MockWorkflowRepository_UpdateStatus_Call {
	return &MockWorkflowRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, tenantID, id, status, expectedRowVersion)}
}

func (_c *MockWorkflowRepository_UpdateStatus_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, status string, expectedRowVersion int)) *MockWorkflowRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockWorkflowRepository_UpdateStatus_Call) Return(_a0 error) *MockWorkflowRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflowRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, int) error) *MockWorkflowRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkflowRepository creates a new instance of MockWorkflowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowRepository {
	mock := &MockWorkflowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
