// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "flowforge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockVersionRepository is an autogenerated mock type for the VersionRepository type
type MockVersionRepository struct {
	mock.Mock
}

type MockVersionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionRepository) EXPECT() *MockVersionRepository_Expecter {
	return &MockVersionRepository_Expecter{mock: &_m.Mock}
}

// CreateVersion provides a mock function with given fields: ctx, v
func (_m *MockVersionRepository) CreateVersion(ctx context.Context, v *domain.WorkflowVersion) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for CreateVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WorkflowVersion) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVersionRepository_CreateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVersion'
type MockVersionRepository_CreateVersion_Call struct {
	*mock.Call
}

// CreateVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - v *domain.WorkflowVersion
func (_e *MockVersionRepository_Expecter) CreateVersion(ctx interface{}, v interface{}) *MockVersionRepository_CreateVersion_Call {
	return &MockVersionRepository_CreateVersion_Call{Call: _e.mock.On("CreateVersion", ctx, v)}
}

func (_c *MockVersionRepository_CreateVersion_Call) Run(run func(ctx context.Context, v *domain.WorkflowVersion)) *MockVersionRepository_CreateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.WorkflowVersion))
	})
	return _c
}

func (_c *MockVersionRepository_CreateVersion_Call) Return(_a0 error) *MockVersionRepository_CreateVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVersionRepository_CreateVersion_Call) RunAndReturn(run func(context.Context, *domain.WorkflowVersion) error) *MockVersionRepository_CreateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// FindDraftVersion provides a mock function with given fields: ctx, tenantID, workflowID
func (_m *MockVersionRepository) FindDraftVersion(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID) (*domain.WorkflowVersion, error) {
	ret := _m.Called(ctx, tenantID, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for FindDraftVersion")
	}

	var r0 *domain.WorkflowVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.WorkflowVersion, error)); ok {
		return rf(ctx, tenantID, workflowID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.WorkflowVersion); ok {
		r0 = rf(ctx, tenantID, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkflowVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersionRepository_FindDraftVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDraftVersion'
type MockVersionRepository_FindDraftVersion_Call struct {
	*mock.Call
}

// FindDraftVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - workflowID uuid.UUID
func (_e *MockVersionRepository_Expecter) FindDraftVersion(ctx interface{}, tenantID interface{}, workflowID interface{}) *MockVersionRepository_FindDraftVersion_Call {
	return &MockVersionRepository_FindDraftVersion_Call{Call: _e.mock.On("FindDraftVersion", ctx, tenantID, workflowID)}
}

func (_c *MockVersionRepository_FindDraftVersion_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID)) *MockVersionRepository_FindDraftVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockVersionRepository_FindDraftVersion_Call) Return(_a0 *domain.WorkflowVersion, _a1 error) *MockVersionRepository_FindDraftVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersionRepository_FindDraftVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.WorkflowVersion, error)) *MockVersionRepository_FindDraftVersion_Call {
	_c.Call.Return(run)
	return _c
}

// FindVersionByID provides a mock function with given fields: ctx, tenantID, workflowID, versionID
func (_m *MockVersionRepository) FindVersionByID(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID, versionID uuid.UUID) (*domain.WorkflowVersion, error) {
	ret := _m.Called(ctx, tenantID, workflowID, versionID)

	if len(ret) == 0 {
		panic("no return value specified for FindVersionByID")
	}

	var r0 *domain.WorkflowVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*domain.WorkflowVersion, error)); ok {
		return rf(ctx, tenantID, workflowID, versionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) *domain.WorkflowVersion); ok {
		r0 = rf(ctx, tenantID, workflowID, versionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkflowVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, workflowID, versionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersionRepository_FindVersionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVersionByID'
type MockVersionRepository_FindVersionByID_Call struct {
	*mock.Call
}

// FindVersionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - workflowID uuid.UUID
//   - versionID uuid.UUID
func (_e *MockVersionRepository_Expecter) FindVersionByID(ctx interface{}, tenantID interface{}, workflowID interface{}, versionID interface{}) *MockVersionRepository_FindVersionByID_Call {
	return &MockVersionRepository_FindVersionByID_Call{Call: _e.mock.On("FindVersionByID", ctx, tenantID, workflowID, versionID)}
}

func (_c *MockVersionRepository_FindVersionByID_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID, versionID uuid.UUID)) *MockVersionRepository_FindVersionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockVersionRepository_FindVersionByID_Call) Return(_a0 *domain.WorkflowVersion, _a1 error) *MockVersionRepository_FindVersionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersionRepository_FindVersionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*domain.WorkflowVersion, error)) *MockVersionRepository_FindVersionByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListVersions provides a mock function with given fields: ctx, tenantID, workflowID
func (_m *MockVersionRepository) ListVersions(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID) ([]*domain.WorkflowVersion, error) {
	ret := _m.Called(ctx, tenantID, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []*domain.WorkflowVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*domain.WorkflowVersion, error)); ok {
		return rf(ctx, tenantID, workflowID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*domain.WorkflowVersion); ok {
		r0 = rf(ctx, tenantID, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.WorkflowVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersionRepository_ListVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVersions'
type MockVersionRepository_ListVersions_Call struct {
	*mock.Call
}

// ListVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - workflowID uuid.UUID
func (_e *MockVersionRepository_Expecter) ListVersions(ctx interface{}, tenantID interface{}, workflowID interface{}) *MockVersionRepository_ListVersions_Call {
	return &MockVersionRepository_ListVersions_Call{Call: _e.mock.On("ListVersions", ctx, tenantID, workflowID)}
}

func (_c *MockVersionRepository_ListVersions_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID)) *MockVersionRepository_ListVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockVersionRepository_ListVersions_Call) Return(_a0 []*domain.WorkflowVersion, _a1 error) *MockVersionRepository_ListVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersionRepository_ListVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]*domain.WorkflowVersion, error)) *MockVersionRepository_ListVersions_Call {
	_c.Call.Return(run)
	return _c
}

// LoadGraph provides a mock function with given fields: ctx, tenantID, versionID
func (_m *MockVersionRepository) LoadGraph(ctx context.Context, tenantID uuid.UUID, versionID uuid.UUID) ([]domain.WorkflowNode, []domain.WorkflowEdge, error) {
	ret := _m.Called(ctx, tenantID, versionID)

	if len(ret) == 0 {
		panic("no return value specified for LoadGraph")
	}

	var r0 []domain.WorkflowNode
	var r1 []domain.WorkflowEdge
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]domain.WorkflowNode, []domain.WorkflowEdge, error)); ok {
		return rf(ctx, tenantID, versionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []domain.WorkflowNode); ok {
		r0 = rf(ctx, tenantID, versionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WorkflowNode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) []domain.WorkflowEdge); ok {
		r1 = rf(ctx, tenantID, versionID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]domain.WorkflowEdge)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r2 = rf(ctx, tenantID, versionID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockVersionRepository_LoadGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadGraph'
type MockVersionRepository_LoadGraph_Call struct {
	*mock.Call
}

// LoadGraph is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - versionID uuid.UUID
func (_e *MockVersionRepository_Expecter) LoadGraph(ctx interface{}, tenantID interface{}, versionID interface{}) *MockVersionRepository_LoadGraph_Call {
	return &MockVersionRepository_LoadGraph_Call{Call: _e.mock.On("LoadGraph", ctx, tenantID, versionID)}
}

func (_c *MockVersionRepository_LoadGraph_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, versionID uuid.UUID)) *MockVersionRepository_LoadGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockVersionRepository_LoadGraph_Call) Return(_a0 []domain.WorkflowNode, _a1 []domain.WorkflowEdge, _a2 error) *MockVersionRepository_LoadGraph_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockVersionRepository_LoadGraph_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]domain.WorkflowNode, []domain.WorkflowEdge, error)) *MockVersionRepository_LoadGraph_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function with given fields: ctx, tenantID, versionID, checksum, snapshot, publishedAt
func (_m *MockVersionRepository) MarkPublished(ctx context.Context, tenantID uuid.UUID, versionID uuid.UUID, checksum string, snapshot []byte, publishedAt time.Time) error {
	ret := _m.Called(ctx, tenantID, versionID, checksum, snapshot, publishedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, []byte, time.Time) error); ok {
		r0 = rf(ctx, tenantID, versionID, checksum, snapshot, publishedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVersionRepository_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type MockVersionRepository_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - versionID uuid.UUID
//   - checksum string
//   - snapshot []byte
//   - publishedAt time.Time
func (_e *MockVersionRepository_Expecter) MarkPublished(ctx interface{}, tenantID interface{}, versionID interface{}, checksum interface{}, snapshot interface{}, publishedAt interface{}) *MockVersionRepository_MarkPublished_Call {
	return &MockVersionRepository_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, tenantID, versionID, checksum, snapshot, publishedAt)}
}

func (_c *MockVersionRepository_MarkPublished_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, versionID uuid.UUID, checksum string, snapshot []byte, publishedAt time.Time)) *MockVersionRepository_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].([]byte), args[5].(time.Time))
	})
	return _c
}

func (_c *MockVersionRepository_MarkPublished_Call) Return(_a0 error) *MockVersionRepository_MarkPublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVersionRepository_MarkPublished_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, []byte, time.Time) error) *MockVersionRepository_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// MaxVersionNumber provides a mock function with given fields: ctx, tenantID, workflowID
func (_m *MockVersionRepository) MaxVersionNumber(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, tenantID, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for MaxVersionNumber")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (int, error)); ok {
		return rf(ctx, tenantID, workflowID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) int); ok {
		r0 = rf(ctx, tenantID, workflowID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersionRepository_MaxVersionNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxVersionNumber'
type MockVersionRepository_MaxVersionNumber_Call struct {
	*mock.Call
}

// MaxVersionNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - workflowID uuid.UUID
func (_e *MockVersionRepository_Expecter) MaxVersionNumber(ctx interface{}, tenantID interface{}, workflowID interface{}) *MockVersionRepository_MaxVersionNumber_Call {
	return &MockVersionRepository_MaxVersionNumber_Call{Call: _e.mock.On("MaxVersionNumber", ctx, tenantID, workflowID)}
}

func (_c *MockVersionRepository_MaxVersionNumber_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID)) *MockVersionRepository_MaxVersionNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockVersionRepository_MaxVersionNumber_Call) Return(_a0 int, _a1 error) *MockVersionRepository_MaxVersionNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersionRepository_MaxVersionNumber_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (int, error)) *MockVersionRepository_MaxVersionNumber_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceGraph provides a mock function with given fields: ctx, tenantID, versionID, nodes, edges
func (_m *MockVersionRepository) ReplaceGraph(ctx context.Context, tenantID uuid.UUID, versionID uuid.UUID, nodes []domain.WorkflowNode, edges []domain.WorkflowEdge) error {
	ret := _m.Called(ctx, tenantID, versionID, nodes, edges)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceGraph")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, []domain.WorkflowNode, []domain.WorkflowEdge) error); ok {
		r0 = rf(ctx, tenantID, versionID, nodes, edges)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVersionRepository_ReplaceGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceGraph'
type MockVersionRepository_ReplaceGraph_Call struct {
	*mock.Call
}

// ReplaceGraph is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - versionID uuid.UUID
//   - nodes []domain.WorkflowNode
//   - edges []domain.WorkflowEdge
func (_e *MockVersionRepository_Expecter) ReplaceGraph(ctx interface{}, tenantID interface{}, versionID interface{}, nodes interface{}, edges interface{}) *MockVersionRepository_ReplaceGraph_Call {
	return &MockVersionRepository_ReplaceGraph_Call{Call: _e.mock.On("ReplaceGraph", ctx, tenantID, versionID, nodes, edges)}
}

func (_c *MockVersionRepository_ReplaceGraph_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, versionID uuid.UUID, nodes []domain.WorkflowNode, edges []domain.WorkflowEdge)) *MockVersionRepository_ReplaceGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].([]domain.WorkflowNode), args[4].([]domain.WorkflowEdge))
	})
	return _c
}

func (_c *MockVersionRepository_ReplaceGraph_Call) Return(_a0 error) *MockVersionRepository_ReplaceGraph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVersionRepository_ReplaceGraph_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, []domain.WorkflowNode, []domain.WorkflowEdge) error) *MockVersionRepository_ReplaceGraph_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVersionRepository creates a new instance of MockVersionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionRepository {
	mock := &MockVersionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
