// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "flowforge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	workflow "flowforge/internal/workflow"
)

// MockWorkflowUseCase is an autogenerated mock type for the WorkflowUseCase type
type MockWorkflowUseCase struct {
	mock.Mock
}

type MockWorkflowUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowUseCase) EXPECT() *MockWorkflowUseCase_Expecter {
	return &MockWorkflowUseCase_Expecter{mock: &_m.Mock}
}

// ArchiveWorkflow provides a mock function with given fields: ctx, cmd
func (_m *MockWorkflowUseCase) ArchiveWorkflow(ctx context.Context, cmd workflow.ArchiveWorkflowCommand) (*domain.Workflow, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveWorkflow")
	}

	var r0 *domain.Workflow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workflow.ArchiveWorkflowCommand) (*domain.Workflow, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workflow.ArchiveWorkflowCommand) *domain.Workflow); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workflow.ArchiveWorkflowCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowUseCase_ArchiveWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveWorkflow'
type MockWorkflowUseCase_ArchiveWorkflow_Call struct {
	*mock.Call
}

// ArchiveWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workflow.ArchiveWorkflowCommand
func (_e *MockWorkflowUseCase_Expecter) ArchiveWorkflow(ctx interface{}, cmd interface{}) *MockWorkflowUseCase_ArchiveWorkflow_Call {
	return &MockWorkflowUseCase_ArchiveWorkflow_Call{Call: _e.mock.On("ArchiveWorkflow", ctx, cmd)}
}

func (_c *MockWorkflowUseCase_ArchiveWorkflow_Call) Run(run func(ctx context.Context, cmd workflow.ArchiveWorkflowCommand)) *MockWorkflowUseCase_ArchiveWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workflow.ArchiveWorkflowCommand))
	})
	return _c
}

func (_c *MockWorkflowUseCase_ArchiveWorkflow_Call) Return(_a0 *domain.Workflow, _a1 error) *MockWorkflowUseCase_ArchiveWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowUseCase_ArchiveWorkflow_Call) RunAndReturn(run func(context.Context, workflow.ArchiveWorkflowCommand) (*domain.Workflow, error)) *MockWorkflowUseCase_ArchiveWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkflow provides a mock function with given fields: ctx, cmd
func (_m *MockWorkflowUseCase) CreateWorkflow(ctx context.Context, cmd workflow.CreateWorkflowCommand) (*domain.Workflow, *domain.WorkflowVersion, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkflow")
	}

	var r0 *domain.Workflow
	var r1 *domain.WorkflowVersion
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, workflow.CreateWorkflowCommand) (*domain.Workflow, *domain.WorkflowVersion, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workflow.CreateWorkflowCommand) *domain.Workflow); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workflow.CreateWorkflowCommand) *domain.WorkflowVersion); ok {
		r1 = rf(ctx, cmd)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.WorkflowVersion)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, workflow.CreateWorkflowCommand) error); ok {
		r2 = rf(ctx, cmd)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWorkflowUseCase_CreateWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkflow'
type MockWorkflowUseCase_CreateWorkflow_Call struct {
	*mock.Call
}

// CreateWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workflow.CreateWorkflowCommand
func (_e *MockWorkflowUseCase_Expecter) CreateWorkflow(ctx interface{}, cmd interface{}) *MockWorkflowUseCase_CreateWorkflow_Call {
	return &MockWorkflowUseCase_CreateWorkflow_Call{Call: _e.mock.On("CreateWorkflow", ctx, cmd)}
}

func (_c *MockWorkflowUseCase_CreateWorkflow_Call) Run(run func(ctx context.Context, cmd workflow.CreateWorkflowCommand)) *MockWorkflowUseCase_CreateWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workflow.CreateWorkflowCommand))
	})
	return _c
}

func (_c *MockWorkflowUseCase_CreateWorkflow_Call) Return(_a0 *domain.Workflow, _a1 *domain.WorkflowVersion, _a2 error) *MockWorkflowUseCase_CreateWorkflow_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockWorkflowUseCase_CreateWorkflow_Call) RunAndReturn(run func(context.Context, workflow.CreateWorkflowCommand) (*domain.Workflow, *domain.WorkflowVersion, error)) *MockWorkflowUseCase_CreateWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields: ctx, tenantID, workflowID, versionID
func (_m *MockWorkflowUseCase) GetVersion(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID, versionID uuid.UUID) (*workflow.VersionDetail, error) {
	ret := _m.Called(ctx, tenantID, workflowID, versionID)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *workflow.VersionDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*workflow.VersionDetail, error)); ok {
		return rf(ctx, tenantID, workflowID, versionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) *workflow.VersionDetail); ok {
		r0 = rf(ctx, tenantID, workflowID, versionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.VersionDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, workflowID, versionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowUseCase_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockWorkflowUseCase_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - workflowID uuid.UUID
//   - versionID uuid.UUID
func (_e *MockWorkflowUseCase_Expecter) GetVersion(ctx interface{}, tenantID interface{}, workflowID interface{}, versionID interface{}) *MockWorkflowUseCase_GetVersion_Call {
	return &MockWorkflowUseCase_GetVersion_Call{Call: _e.mock.On("GetVersion", ctx, tenantID, workflowID, versionID)}
}

func (_c *MockWorkflowUseCase_GetVersion_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID, versionID uuid.UUID)) *MockWorkflowUseCase_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkflowUseCase_GetVersion_Call) Return(_a0 *workflow.VersionDetail, _a1 error) *MockWorkflowUseCase_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowUseCase_GetVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*workflow.VersionDetail, error)) *MockWorkflowUseCase_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflow provides a mock function with given fields: ctx, tenantID, workflowID
func (_m *MockWorkflowUseCase) GetWorkflow(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID) (*domain.Workflow, error) {
	ret := _m.Called(ctx, tenantID, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflow")
	}

	var r0 *domain.Workflow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Workflow, error)); ok {
		return rf(ctx, tenantID, workflowID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Workflow); ok {
		r0 = rf(ctx, tenantID, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowUseCase_GetWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflow'
type MockWorkflowUseCase_GetWorkflow_Call struct {
	*mock.Call
}

// GetWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - workflowID uuid.UUID
func (_e *MockWorkflowUseCase_Expecter) GetWorkflow(ctx interface{}, tenantID interface{}, workflowID interface{}) *MockWorkflowUseCase_GetWorkflow_Call {
	return &MockWorkflowUseCase_GetWorkflow_Call{Call: _e.mock.On("GetWorkflow", ctx, tenantID, workflowID)}
}

func (_c *MockWorkflowUseCase_GetWorkflow_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID)) *MockWorkflowUseCase_GetWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkflowUseCase_GetWorkflow_Call) Return(_a0 *domain.Workflow, _a1 error) *MockWorkflowUseCase_GetWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowUseCase_GetWorkflow_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Workflow, error)) *MockWorkflowUseCase_GetWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// ListVersions provides a mock function with given fields: ctx, tenantID, workflowID
func (_m *MockWorkflowUseCase) ListVersions(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID) ([]*domain.WorkflowVersion, error) {
	ret := _m.Called(ctx, tenantID, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []*domain.WorkflowVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*domain.WorkflowVersion, error)); ok {
		return rf(ctx, tenantID, workflowID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*domain.WorkflowVersion); ok {
		r0 = rf(ctx, tenantID, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.WorkflowVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowUseCase_ListVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVersions'
type MockWorkflowUseCase_ListVersions_Call struct {
	*mock.Call
}

// ListVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - workflowID uuid.UUID
func (_e *MockWorkflowUseCase_Expecter) ListVersions(ctx interface{}, tenantID interface{}, workflowID interface{}) *MockWorkflowUseCase_ListVersions_Call {
	return &MockWorkflowUseCase_ListVersions_Call{Call: _e.mock.On("ListVersions", ctx, tenantID, workflowID)}
}

func (_c *MockWorkflowUseCase_ListVersions_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID)) *MockWorkflowUseCase_ListVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkflowUseCase_ListVersions_Call) Return(_a0 []*domain.WorkflowVersion, _a1 error) *MockWorkflowUseCase_ListVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowUseCase_ListVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]*domain.WorkflowVersion, error)) *MockWorkflowUseCase_ListVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkflows provides a mock function with given fields: ctx, q
func (_m *MockWorkflowUseCase) ListWorkflows(ctx context.Context, q workflow.ListWorkflowsQuery) (*workflow.PaginatedWorkflows, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkflows")
	}

	var r0 *workflow.PaginatedWorkflows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workflow.ListWorkflowsQuery) (*workflow.PaginatedWorkflows, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workflow.ListWorkflowsQuery) *workflow.PaginatedWorkflows); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.PaginatedWorkflows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workflow.ListWorkflowsQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowUseCase_ListWorkflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkflows'
type MockWorkflowUseCase_ListWorkflows_Call struct {
	*mock.Call
}

// ListWorkflows is a helper method to define mock.On call
//   - ctx context.Context
//   - q workflow.ListWorkflowsQuery
func (_e *MockWorkflowUseCase_Expecter) ListWorkflows(ctx interface{}, q interface{}) *MockWorkflowUseCase_ListWorkflows_Call {
	return &MockWorkflowUseCase_ListWorkflows_Call{Call: _e.mock.On("ListWorkflows", ctx, q)}
}

func (_c *MockWorkflowUseCase_ListWorkflows_Call) Run(run func(ctx context.Context, q workflow.ListWorkflowsQuery)) *MockWorkflowUseCase_ListWorkflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workflow.ListWorkflowsQuery))
	})
	return _c
}

func (_c *MockWorkflowUseCase_ListWorkflows_Call) Return(_a0 *workflow.PaginatedWorkflows, _a1 error) *MockWorkflowUseCase_ListWorkflows_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowUseCase_ListWorkflows_Call) RunAndReturn(run func(context.Context, workflow.ListWorkflowsQuery) (*workflow.PaginatedWorkflows, error)) *MockWorkflowUseCase_ListWorkflows_Call {
	_c.Call.Return(run)
	return _c
}

// PublishVersion provides a mock function with given fields: ctx, cmd
func (_m *MockWorkflowUseCase) PublishVersion(ctx context.Context, cmd workflow.PublishCommand) (*workflow.PublishResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for PublishVersion")
	}

	var r0 *workflow.PublishResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workflow.PublishCommand) (*workflow.PublishResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workflow.PublishCommand) *workflow.PublishResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.PublishResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workflow.PublishCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowUseCase_PublishVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishVersion'
type MockWorkflowUseCase_PublishVersion_Call struct {
	*mock.Call
}

// PublishVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workflow.PublishCommand
func (_e *MockWorkflowUseCase_Expecter) PublishVersion(ctx interface{}, cmd interface{}) *MockWorkflowUseCase_PublishVersion_Call {
	return &MockWorkflowUseCase_PublishVersion_Call{Call: _e.mock.On("PublishVersion", ctx, cmd)}
}

func (_c *MockWorkflowUseCase_PublishVersion_Call) Run(run func(ctx context.Context, cmd workflow.PublishCommand)) *MockWorkflowUseCase_PublishVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workflow.PublishCommand))
	})
	return _c
}

func (_c *MockWorkflowUseCase_PublishVersion_Call) Return(_a0 *workflow.PublishResult, _a1 error) *MockWorkflowUseCase_PublishVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowUseCase_PublishVersion_Call) RunAndReturn(run func(context.Context, workflow.PublishCommand) (*workflow.PublishResult, error)) *MockWorkflowUseCase_PublishVersion_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackVersion provides a mock function with given fields: ctx, cmd
func (_m *MockWorkflowUseCase) RollbackVersion(ctx context.Context, cmd workflow.RollbackCommand) (*workflow.RollbackResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RollbackVersion")
	}

	var r0 *workflow.RollbackResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workflow.RollbackCommand) (*workflow.RollbackResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workflow.RollbackCommand) *workflow.RollbackResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.RollbackResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workflow.RollbackCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowUseCase_RollbackVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackVersion'
type MockWorkflowUseCase_RollbackVersion_Call struct {
	*mock.Call
}

// RollbackVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workflow.RollbackCommand
func (_e *MockWorkflowUseCase_Expecter) RollbackVersion(ctx interface{}, cmd interface{}) *MockWorkflowUseCase_RollbackVersion_Call {
	return &MockWorkflowUseCase_RollbackVersion_Call{Call: _e.mock.On("RollbackVersion", ctx, cmd)}
}

func (_c *MockWorkflowUseCase_RollbackVersion_Call) Run(run func(ctx context.Context, cmd workflow.RollbackCommand)) *MockWorkflowUseCase_RollbackVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workflow.RollbackCommand))
	})
	return _c
}

func (_c *MockWorkflowUseCase_RollbackVersion_Call) Return(_a0 *workflow.RollbackResult, _a1 error) *MockWorkflowUseCase_RollbackVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowUseCase_RollbackVersion_Call) RunAndReturn(run func(context.Context, workflow.RollbackCommand) (*workflow.RollbackResult, error)) *MockWorkflowUseCase_RollbackVersion_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDraft provides a mock function with given fields: ctx, cmd
func (_m *MockWorkflowUseCase) SaveDraft(ctx context.Context, cmd workflow.SaveDraftCommand) (*workflow.SaveDraftResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for SaveDraft")
	}

	var r0 *workflow.SaveDraftResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workflow.SaveDraftCommand) (*workflow.SaveDraftResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workflow.SaveDraftCommand) *workflow.SaveDraftResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.SaveDraftResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workflow.SaveDraftCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowUseCase_SaveDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDraft'
type MockWorkflowUseCase_SaveDraft_Call struct {
	*mock.Call
}

// SaveDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workflow.SaveDraftCommand
func (_e *MockWorkflowUseCase_Expecter) SaveDraft(ctx interface{}, cmd interface{}) *MockWorkflowUseCase_SaveDraft_Call {
	return &MockWorkflowUseCase_SaveDraft_Call{Call: _e.mock.On("SaveDraft", ctx, cmd)}
}

func (_c *MockWorkflowUseCase_SaveDraft_Call) Run(run func(ctx context.Context, cmd workflow.SaveDraftCommand)) *MockWorkflowUseCase_SaveDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workflow.SaveDraftCommand))
	})
	return _c
}

func (_c *MockWorkflowUseCase_SaveDraft_Call) Return(_a0 *workflow.SaveDraftResult, _a1 error) *MockWorkflowUseCase_SaveDraft_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowUseCase_SaveDraft_Call) RunAndReturn(run func(context.Context, workflow.SaveDraftCommand) (*workflow.SaveDraftResult, error)) *MockWorkflowUseCase_SaveDraft_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkflow provides a mock function with given fields: ctx, cmd
func (_m *MockWorkflowUseCase) UpdateWorkflow(ctx context.Context, cmd workflow.UpdateWorkflowCommand) (*domain.Workflow, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkflow")
	}

	var r0 *domain.Workflow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workflow.UpdateWorkflowCommand) (*domain.Workflow, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workflow.UpdateWorkflowCommand) *domain.Workflow); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workflow.UpdateWorkflowCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowUseCase_UpdateWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkflow'
type MockWorkflowUseCase_UpdateWorkflow_Call struct {
	*mock.Call
}

// UpdateWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd workflow.UpdateWorkflowCommand
func (_e *MockWorkflowUseCase_Expecter) UpdateWorkflow(ctx interface{}, cmd interface{}) *MockWorkflowUseCase_UpdateWorkflow_Call {
	return &MockWorkflowUseCase_UpdateWorkflow_Call{Call: _e.mock.On("UpdateWorkflow", ctx, cmd)}
}

func (_c *MockWorkflowUseCase_UpdateWorkflow_Call) Run(run func(ctx context.Context, cmd workflow.UpdateWorkflowCommand)) *MockWorkflowUseCase_UpdateWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workflow.UpdateWorkflowCommand))
	})
	return _c
}

func (_c *MockWorkflowUseCase_UpdateWorkflow_Call) Return(_a0 *domain.Workflow, _a1 error) *MockWorkflowUseCase_UpdateWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowUseCase_UpdateWorkflow_Call) RunAndReturn(run func(context.Context, workflow.UpdateWorkflowCommand) (*domain.Workflow, error)) *MockWorkflowUseCase_UpdateWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkflowUseCase creates a new instance of MockWorkflowUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowUseCase {
	mock := &MockWorkflowUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
