// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "flowforge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTenantRepository is an autogenerated mock type for the TenantRepository type
type MockTenantRepository struct {
	mock.Mock
}

type MockTenantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantRepository) EXPECT() *MockTenantRepository_Expecter {
	return &MockTenantRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTenantRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Tenant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Tenant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Tenant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTenantRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTenantRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTenantRepository_FindByID_Call {
	return &MockTenantRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTenantRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTenantRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTenantRepository_FindByID_Call) Return(_a0 *domain.Tenant, _a1 error) *MockTenantRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Tenant, error)) *MockTenantRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function with given fields: ctx, slug
func (_m *MockTenantRepository) FindBySlug(ctx context.Context, slug string) (*domain.Tenant, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *domain.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Tenant, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Tenant); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantRepository_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type MockTenantRepository_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockTenantRepository_Expecter) FindBySlug(ctx interface{}, slug interface{}) *MockTenantRepository_FindBySlug_Call {
	return &MockTenantRepository_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *MockTenantRepository_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockTenantRepository_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTenantRepository_FindBySlug_Call) Return(_a0 *domain.Tenant, _a1 error) *MockTenantRepository_FindBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantRepository_FindBySlug_Call) RunAndReturn(run func(context.Context, string) (*domain.Tenant, error)) *MockTenantRepository_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTenantRepository creates a new instance of MockTenantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantRepository {
	mock := &MockTenantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
