// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "flowforge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTenantUseCase is an autogenerated mock type for the TenantUseCase type
type MockTenantUseCase struct {
	mock.Mock
}

type MockTenantUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantUseCase) EXPECT() *MockTenantUseCase_Expecter {
	return &MockTenantUseCase_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTenantUseCase) GetByID(ctx context.Context, id uuid.UUID) (*domain.Tenant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Tenant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Tenant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantUseCase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTenantUseCase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTenantUseCase_Expecter) GetByID(ctx interface{}, id interface{}) *MockTenantUseCase_GetByID_Call {
	return &MockTenantUseCase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTenantUseCase_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTenantUseCase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTenantUseCase_GetByID_Call) Return(_a0 *domain.Tenant, _a1 error) *MockTenantUseCase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantUseCase_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Tenant, error)) *MockTenantUseCase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function with given fields: ctx, slug
func (_m *MockTenantUseCase) GetBySlug(ctx context.Context, slug string) (*domain.Tenant, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *domain.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Tenant, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Tenant); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantUseCase_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockTenantUseCase_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockTenantUseCase_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockTenantUseCase_GetBySlug_Call {
	return &MockTenantUseCase_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockTenantUseCase_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockTenantUseCase_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTenantUseCase_GetBySlug_Call) Return(_a0 *domain.Tenant, _a1 error) *MockTenantUseCase_GetBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantUseCase_GetBySlug_Call) RunAndReturn(run func(context.Context, string) (*domain.Tenant, error)) *MockTenantUseCase_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTenantUseCase creates a new instance of MockTenantUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantUseCase {
	mock := &MockTenantUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
