// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	auth "flowforge/internal/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockJWTService is an autogenerated mock type for the JWTService type
type MockJWTService struct {
	mock.Mock
}

type MockJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTService) EXPECT() *MockJWTService_Expecter {
	return &MockJWTService_Expecter{mock: &_m.Mock}
}

// GenerateTokenPair provides a mock function with given fields: userID, tenantID, sessionID, email, role
func (_m *MockJWTService) GenerateTokenPair(userID uuid.UUID, tenantID uuid.UUID, sessionID uuid.UUID, email string, role string) (*auth.TokenPair, error) {
	ret := _m.Called(userID, tenantID, sessionID, email, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 *auth.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, uuid.UUID, string, string) (*auth.TokenPair, error)); ok {
		return rf(userID, tenantID, sessionID, email, role)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, uuid.UUID, string, string) *auth.TokenPair); ok {
		r0 = rf(userID, tenantID, sessionID, email, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, uuid.UUID, string, string) error); ok {
		r1 = rf(userID, tenantID, sessionID, email, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type MockJWTService_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - userID uuid.UUID
//   - tenantID uuid.UUID
//   - sessionID uuid.UUID
//   - email string
//   - role string
func (_e *MockJWTService_Expecter) GenerateTokenPair(userID interface{}, tenantID interface{}, sessionID interface{}, email interface{}, role interface{}) *MockJWTService_GenerateTokenPair_Call {
	return &MockJWTService_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", userID, tenantID, sessionID, email, role)}
}

func (_c *MockJWTService_GenerateTokenPair_Call) Run(run func(userID uuid.UUID, tenantID uuid.UUID, sessionID uuid.UUID, email string, role string)) *MockJWTService_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockJWTService_GenerateTokenPair_Call) Return(_a0 *auth.TokenPair, _a1 error) *MockJWTService_GenerateTokenPair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_GenerateTokenPair_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID, uuid.UUID, string, string) (*auth.TokenPair, error)) *MockJWTService_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: tokenStr
func (_m *MockJWTService) ValidateAccessToken(tokenStr string) (*auth.CustomClaims, error) {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *auth.CustomClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.CustomClaims, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.CustomClaims); ok {
		r0 = rf(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CustomClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockJWTService_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockJWTService_Expecter) ValidateAccessToken(tokenStr interface{}) *MockJWTService_ValidateAccessToken_Call {
	return &MockJWTService_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", tokenStr)}
}

func (_c *MockJWTService_ValidateAccessToken_Call) Run(run func(tokenStr string)) *MockJWTService_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTService_ValidateAccessToken_Call) Return(_a0 *auth.CustomClaims, _a1 error) *MockJWTService_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_ValidateAccessToken_Call) RunAndReturn(run func(string) (*auth.CustomClaims, error)) *MockJWTService_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: tokenStr
func (_m *MockJWTService) ValidateRefreshToken(tokenStr string) (*auth.CustomClaims, error) {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *auth.CustomClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.CustomClaims, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.CustomClaims); ok {
		r0 = rf(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CustomClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockJWTService_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockJWTService_Expecter) ValidateRefreshToken(tokenStr interface{}) *MockJWTService_ValidateRefreshToken_Call {
	return &MockJWTService_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", tokenStr)}
}

func (_c *MockJWTService_ValidateRefreshToken_Call) Run(run func(tokenStr string)) *MockJWTService_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTService_ValidateRefreshToken_Call) Return(_a0 *auth.CustomClaims, _a1 error) *MockJWTService_ValidateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_ValidateRefreshToken_Call) RunAndReturn(run func(string) (*auth.CustomClaims, error)) *MockJWTService_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTService creates a new instance of MockJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTService {
	mock := &MockJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
