// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "flowforge/internal/auth"

	domain "flowforge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuthUseCase is an autogenerated mock type for the AuthUseCase type
type MockAuthUseCase struct {
	mock.Mock
}

type MockAuthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUseCase) EXPECT() *MockAuthUseCase_Expecter {
	return &MockAuthUseCase_Expecter{mock: &_m.Mock}
}

// GetMe provides a mock function with given fields: ctx, tenantID, userID
func (_m *MockAuthUseCase) GetMe(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, tenantID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUseCase_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MockAuthUseCase_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
func (_e *MockAuthUseCase_Expecter) GetMe(ctx interface{}, tenantID interface{}, userID interface{}) *MockAuthUseCase_GetMe_Call {
	return &MockAuthUseCase_GetMe_Call{Call: _e.mock.On("GetMe", ctx, tenantID, userID)}
}

func (_c *MockAuthUseCase_GetMe_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID)) *MockAuthUseCase_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthUseCase_GetMe_Call) Return(_a0 *domain.User, _a1 error) *MockAuthUseCase_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUseCase_GetMe_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.User, error)) *MockAuthUseCase_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function with given fields: ctx, tenantID, userID, page, pageSize
func (_m *MockAuthUseCase) ListSessions(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, page int, pageSize int) (*auth.PaginatedSessions, error) {
	ret := _m.Called(ctx, tenantID, userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 *auth.PaginatedSessions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) (*auth.PaginatedSessions, error)); ok {
		return rf(ctx, tenantID, userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) *auth.PaginatedSessions); ok {
		r0 = rf(ctx, tenantID, userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.PaginatedSessions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, tenantID, userID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUseCase_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockAuthUseCase_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
//   - page int
//   - pageSize int
func (_e *MockAuthUseCase_Expecter) ListSessions(ctx interface{}, tenantID interface{}, userID interface{}, page interface{}, pageSize interface{}) *MockAuthUseCase_ListSessions_Call {
	return &MockAuthUseCase_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, tenantID, userID, page, pageSize)}
}

func (_c *MockAuthUseCase_ListSessions_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, page int, pageSize int)) *MockAuthUseCase_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockAuthUseCase_ListSessions_Call) Return(_a0 *auth.PaginatedSessions, _a1 error) *MockAuthUseCase_ListSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUseCase_ListSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, int) (*auth.PaginatedSessions, error)) *MockAuthUseCase_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, tenantSlug, email, password, ipAddress, userAgent
func (_m *MockAuthUseCase) Login(ctx context.Context, tenantSlug string, email string, password string, ipAddress string, userAgent string) (*auth.AuthResult, error) {
	ret := _m.Called(ctx, tenantSlug, email, password, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*auth.AuthResult, error)); ok {
		return rf(ctx, tenantSlug, email, password, ipAddress, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *auth.AuthResult); ok {
		r0 = rf(ctx, tenantSlug, email, password, ipAddress, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, tenantSlug, email, password, ipAddress, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantSlug string
//   - email string
//   - password string
//   - ipAddress string
//   - userAgent string
func (_e *MockAuthUseCase_Expecter) Login(ctx interface{}, tenantSlug interface{}, email interface{}, password interface{}, ipAddress interface{}, userAgent interface{}) *MockAuthUseCase_Login_Call {
	return &MockAuthUseCase_Login_Call{Call: _e.mock.On("Login", ctx, tenantSlug, email, password, ipAddress, userAgent)}
}

func (_c *MockAuthUseCase_Login_Call) Run(run func(ctx context.Context, tenantSlug string, email string, password string, ipAddress string, userAgent string)) *MockAuthUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockAuthUseCase_Login_Call) Return(_a0 *auth.AuthResult, _a1 error) *MockAuthUseCase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUseCase_Login_Call) RunAndReturn(run func(context.Context, string, string, string, string, string) (*auth.AuthResult, error)) *MockAuthUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, tokenStr
func (_m *MockAuthUseCase) Logout(ctx context.Context, tokenStr string) error {
	ret := _m.Called(ctx, tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenStr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthUseCase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthUseCase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenStr string
func (_e *MockAuthUseCase_Expecter) Logout(ctx interface{}, tokenStr interface{}) *MockAuthUseCase_Logout_Call {
	return &MockAuthUseCase_Logout_Call{Call: _e.mock.On("Logout", ctx, tokenStr)}
}

func (_c *MockAuthUseCase_Logout_Call) Run(run func(ctx context.Context, tokenStr string)) *MockAuthUseCase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthUseCase_Logout_Call) Return(_a0 error) *MockAuthUseCase_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthUseCase_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthUseCase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAllDevices provides a mock function with given fields: ctx, tenantID, userID
func (_m *MockAuthUseCase) LogoutAllDevices(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAllDevices")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthUseCase_LogoutAllDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAllDevices'
type MockAuthUseCase_LogoutAllDevices_Call struct {
	*mock.Call
}

// LogoutAllDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
func (_e *MockAuthUseCase_Expecter) LogoutAllDevices(ctx interface{}, tenantID interface{}, userID interface{}) *MockAuthUseCase_LogoutAllDevices_Call {
	return &MockAuthUseCase_LogoutAllDevices_Call{Call: _e.mock.On("LogoutAllDevices", ctx, tenantID, userID)}
}

func (_c *MockAuthUseCase_LogoutAllDevices_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID)) *MockAuthUseCase_LogoutAllDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthUseCase_LogoutAllDevices_Call) Return(_a0 error) *MockAuthUseCase_LogoutAllDevices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthUseCase_LogoutAllDevices_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockAuthUseCase_LogoutAllDevices_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshTokenStr
func (_m *MockAuthUseCase) Refresh(ctx context.Context, refreshTokenStr string) (*auth.AuthResult, error) {
	ret := _m.Called(ctx, refreshTokenStr)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *auth.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.AuthResult, error)); ok {
		return rf(ctx, refreshTokenStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.AuthResult); ok {
		r0 = rf(ctx, refreshTokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshTokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUseCase_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthUseCase_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshTokenStr string
func (_e *MockAuthUseCase_Expecter) Refresh(ctx interface{}, refreshTokenStr interface{}) *MockAuthUseCase_Refresh_Call {
	return &MockAuthUseCase_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshTokenStr)}
}

func (_c *MockAuthUseCase_Refresh_Call) Run(run func(ctx context.Context, refreshTokenStr string)) *MockAuthUseCase_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthUseCase_Refresh_Call) Return(_a0 *auth.AuthResult, _a1 error) *MockAuthUseCase_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUseCase_Refresh_Call) RunAndReturn(run func(context.Context, string) (*auth.AuthResult, error)) *MockAuthUseCase_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthUseCase creates a new instance of MockAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUseCase {
	mock := &MockAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
