// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenBlacklist is an autogenerated mock type for the TokenBlacklist type
type MockTokenBlacklist struct {
	mock.Mock
}

type MockTokenBlacklist_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenBlacklist) EXPECT() *MockTokenBlacklist_Expecter {
	return &MockTokenBlacklist_Expecter{mock: &_m.Mock}
}

// IsRevoked provides a mock function with given fields: ctx, jti
func (_m *MockTokenBlacklist) IsRevoked(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenBlacklist_IsRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRevoked'
type MockTokenBlacklist_IsRevoked_Call struct {
	*mock.Call
}

// IsRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockTokenBlacklist_Expecter) IsRevoked(ctx interface{}, jti interface{}) *MockTokenBlacklist_IsRevoked_Call {
	return &MockTokenBlacklist_IsRevoked_Call{Call: _e.mock.On("IsRevoked", ctx, jti)}
}

func (_c *MockTokenBlacklist_IsRevoked_Call) Run(run func(ctx context.Context, jti string)) *MockTokenBlacklist_IsRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenBlacklist_IsRevoked_Call) Return(_a0 bool, _a1 error) *MockTokenBlacklist_IsRevoked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenBlacklist_IsRevoked_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTokenBlacklist_IsRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, jti, ttl
func (_m *MockTokenBlacklist) Revoke(ctx context.Context, jti string, ttl time.Duration) error {
	ret := _m.Called(ctx, jti, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, jti, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenBlacklist_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenBlacklist_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - ttl time.Duration
func (_e *MockTokenBlacklist_Expecter) Revoke(ctx interface{}, jti interface{}, ttl interface{}) *MockTokenBlacklist_Revoke_Call {
	return &MockTokenBlacklist_Revoke_Call{Call: _e.mock.On("Revoke", ctx, jti, ttl)}
}

func (_c *MockTokenBlacklist_Revoke_Call) Run(run func(ctx context.Context, jti string, ttl time.Duration)) *MockTokenBlacklist_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockTokenBlacklist_Revoke_Call) Return(_a0 error) *MockTokenBlacklist_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenBlacklist_Revoke_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockTokenBlacklist_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenBlacklist creates a new instance of MockTokenBlacklist. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenBlacklist(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenBlacklist {
	mock := &MockTokenBlacklist{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
