// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "flowforge/internal/auth"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, session, ttl
func (_m *MockSessionStore) CreateSession(ctx context.Context, session *auth.UserSession, ttl time.Duration) error {
	ret := _m.Called(ctx, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.UserSession, time.Duration) error); ok {
		r0 = rf(ctx, session, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionStore_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *auth.UserSession
//   - ttl time.Duration
func (_e *MockSessionStore_Expecter) CreateSession(ctx interface{}, session interface{}, ttl interface{}) *MockSessionStore_CreateSession_Call {
	return &MockSessionStore_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session, ttl)}
}

func (_c *MockSessionStore_CreateSession_Call) Run(run func(ctx context.Context, session *auth.UserSession, ttl time.Duration)) *MockSessionStore_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.UserSession), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSessionStore_CreateSession_Call) Return(_a0 error) *MockSessionStore_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_CreateSession_Call) RunAndReturn(run func(context.Context, *auth.UserSession, time.Duration) error) *MockSessionStore_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, tenantID, userID, sessionID
func (_m *MockSessionStore) GetSession(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, sessionID uuid.UUID) (*auth.UserSession, error) {
	ret := _m.Called(ctx, tenantID, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *auth.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*auth.UserSession, error)); ok {
		return rf(ctx, tenantID, userID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) *auth.UserSession); ok {
		r0 = rf(ctx, tenantID, userID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionStore_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
//   - sessionID uuid.UUID
func (_e *MockSessionStore_Expecter) GetSession(ctx interface{}, tenantID interface{}, userID interface{}, sessionID interface{}) *MockSessionStore_GetSession_Call {
	return &MockSessionStore_GetSession_Call{Call: _e.mock.On("GetSession", ctx, tenantID, userID, sessionID)}
}

func (_c *MockSessionStore_GetSession_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, sessionID uuid.UUID)) *MockSessionStore_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionStore_GetSession_Call) Return(_a0 *auth.UserSession, _a1 error) *MockSessionStore_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_GetSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*auth.UserSession, error)) *MockSessionStore_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserRevoked provides a mock function with given fields: ctx, userID, issuedAt
func (_m *MockSessionStore) IsUserRevoked(ctx context.Context, userID uuid.UUID, issuedAt time.Time) (bool, error) {
	ret := _m.Called(ctx, userID, issuedAt)

	if len(ret) == 0 {
		panic("no return value specified for IsUserRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (bool, error)); ok {
		return rf(ctx, userID, issuedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) bool); ok {
		r0 = rf(ctx, userID, issuedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, issuedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_IsUserRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserRevoked'
type MockSessionStore_IsUserRevoked_Call struct {
	*mock.Call
}

// IsUserRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - issuedAt time.Time
func (_e *MockSessionStore_Expecter) IsUserRevoked(ctx interface{}, userID interface{}, issuedAt interface{}) *MockSessionStore_IsUserRevoked_Call {
	return &MockSessionStore_IsUserRevoked_Call{Call: _e.mock.On("IsUserRevoked", ctx, userID, issuedAt)}
}

func (_c *MockSessionStore_IsUserRevoked_Call) Run(run func(ctx context.Context, userID uuid.UUID, issuedAt time.Time)) *MockSessionStore_IsUserRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSessionStore_IsUserRevoked_Call) Return(_a0 bool, _a1 error) *MockSessionStore_IsUserRevoked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_IsUserRevoked_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (bool, error)) *MockSessionStore_IsUserRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserSessions provides a mock function with given fields: ctx, tenantID, userID, page, pageSize
func (_m *MockSessionStore) ListUserSessions(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, page int, pageSize int) ([]*auth.UserSession, int64, error) {
	ret := _m.Called(ctx, tenantID, userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListUserSessions")
	}

	var r0 []*auth.UserSession
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*auth.UserSession, int64, error)); ok {
		return rf(ctx, tenantID, userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) []*auth.UserSession); ok {
		r0 = rf(ctx, tenantID, userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*auth.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, tenantID, userID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, tenantID, userID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSessionStore_ListUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserSessions'
type MockSessionStore_ListUserSessions_Call struct {
	*mock.Call
}

// ListUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
//   - page int
//   - pageSize int
func (_e *MockSessionStore_Expecter) ListUserSessions(ctx interface{}, tenantID interface{}, userID interface{}, page interface{}, pageSize interface{}) *MockSessionStore_ListUserSessions_Call {
	return &MockSessionStore_ListUserSessions_Call{Call: _e.mock.On("ListUserSessions", ctx, tenantID, userID, page, pageSize)}
}

func (_c *MockSessionStore_ListUserSessions_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, page int, pageSize int)) *MockSessionStore_ListUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockSessionStore_ListUserSessions_Call) Return(_a0 []*auth.UserSession, _a1 int64, _a2 error) *MockSessionStore_ListUserSessions_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSessionStore_ListUserSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*auth.UserSession, int64, error)) *MockSessionStore_ListUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserSessions provides a mock function with given fields: ctx, tenantID, userID
func (_m *MockSessionStore) RevokeAllUserSessions(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_RevokeAllUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserSessions'
type MockSessionStore_RevokeAllUserSessions_Call struct {
	*mock.Call
}

// RevokeAllUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
func (_e *MockSessionStore_Expecter) RevokeAllUserSessions(ctx interface{}, tenantID interface{}, userID interface{}) *MockSessionStore_RevokeAllUserSessions_Call {
	return &MockSessionStore_RevokeAllUserSessions_Call{Call: _e.mock.On("RevokeAllUserSessions", ctx, tenantID, userID)}
}

func (_c *MockSessionStore_RevokeAllUserSessions_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID)) *MockSessionStore_RevokeAllUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionStore_RevokeAllUserSessions_Call) Return(_a0 error) *MockSessionStore_RevokeAllUserSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_RevokeAllUserSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockSessionStore_RevokeAllUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, tenantID, userID, sessionID
func (_m *MockSessionStore) RevokeSession(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, userID, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockSessionStore_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
//   - sessionID uuid.UUID
func (_e *MockSessionStore_Expecter) RevokeSession(ctx interface{}, tenantID interface{}, userID interface{}, sessionID interface{}) *MockSessionStore_RevokeSession_Call {
	return &MockSessionStore_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, tenantID, userID, sessionID)}
}

func (_c *MockSessionStore_RevokeSession_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, sessionID uuid.UUID)) *MockSessionStore_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionStore_RevokeSession_Call) Return(_a0 error) *MockSessionStore_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_RevokeSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockSessionStore_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserRevokedBefore provides a mock function with given fields: ctx, userID, revokedAt, ttl
func (_m *MockSessionStore) SetUserRevokedBefore(ctx context.Context, userID uuid.UUID, revokedAt time.Time, ttl time.Duration) error {
	ret := _m.Called(ctx, userID, revokedAt, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRevokedBefore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Duration) error); ok {
		r0 = rf(ctx, userID, revokedAt, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_SetUserRevokedBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserRevokedBefore'
type MockSessionStore_SetUserRevokedBefore_Call struct {
	*mock.Call
}

// SetUserRevokedBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - revokedAt time.Time
//   - ttl time.Duration
func (_e *MockSessionStore_Expecter) SetUserRevokedBefore(ctx interface{}, userID interface{}, revokedAt interface{}, ttl interface{}) *MockSessionStore_SetUserRevokedBefore_Call {
	return &MockSessionStore_SetUserRevokedBefore_Call{Call: _e.mock.On("SetUserRevokedBefore", ctx, userID, revokedAt, ttl)}
}

func (_c *MockSessionStore_SetUserRevokedBefore_Call) Run(run func(ctx context.Context, userID uuid.UUID, revokedAt time.Time, ttl time.Duration)) *MockSessionStore_SetUserRevokedBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockSessionStore_SetUserRevokedBefore_Call) Return(_a0 error) *MockSessionStore_SetUserRevokedBefore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_SetUserRevokedBefore_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Duration) error) *MockSessionStore_SetUserRevokedBefore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
