// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "flowforge/internal/auth"

	domain "flowforge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserUseCase is an autogenerated mock type for the UserUseCase type
type MockUserUseCase struct {
	mock.Mock
}

type MockUserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUseCase) EXPECT() *MockUserUseCase_Expecter {
	return &MockUserUseCase_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, cmd
func (_m *MockUserUseCase) CreateUser(ctx context.Context, cmd auth.CreateUserCommand) (*domain.User, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.CreateUserCommand) (*domain.User, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.CreateUserCommand) *domain.User); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.CreateUserCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUseCase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserUseCase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd auth.CreateUserCommand
func (_e *MockUserUseCase_Expecter) CreateUser(ctx interface{}, cmd interface{}) *MockUserUseCase_CreateUser_Call {
	return &MockUserUseCase_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, cmd)}
}

func (_c *MockUserUseCase_CreateUser_Call) Run(run func(ctx context.Context, cmd auth.CreateUserCommand)) *MockUserUseCase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.CreateUserCommand))
	})
	return _c
}

func (_c *MockUserUseCase_CreateUser_Call) Return(_a0 *domain.User, _a1 error) *MockUserUseCase_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUseCase_CreateUser_Call) RunAndReturn(run func(context.Context, auth.CreateUserCommand) (*domain.User, error)) *MockUserUseCase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, actorID, tenantID, targetID
func (_m *MockUserUseCase) DeleteUser(ctx context.Context, actorID uuid.UUID, tenantID uuid.UUID, targetID uuid.UUID) error {
	ret := _m.Called(ctx, actorID, tenantID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, actorID, tenantID, targetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserUseCase_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserUseCase_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - tenantID uuid.UUID
//   - targetID uuid.UUID
func (_e *MockUserUseCase_Expecter) DeleteUser(ctx interface{}, actorID interface{}, tenantID interface{}, targetID interface{}) *MockUserUseCase_DeleteUser_Call {
	return &MockUserUseCase_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, actorID, tenantID, targetID)}
}

func (_c *MockUserUseCase_DeleteUser_Call) Run(run func(ctx context.Context, actorID uuid.UUID, tenantID uuid.UUID, targetID uuid.UUID)) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserUseCase_DeleteUser_Call) Return(_a0 error) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserUseCase_DeleteUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, tenantID, userID
func (_m *MockUserUseCase) GetUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, tenantID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUseCase_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserUseCase_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
func (_e *MockUserUseCase_Expecter) GetUser(ctx interface{}, tenantID interface{}, userID interface{}) *MockUserUseCase_GetUser_Call {
	return &MockUserUseCase_GetUser_Call{Call: _e.mock.On("GetUser", ctx, tenantID, userID)}
}

func (_c *MockUserUseCase_GetUser_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID)) *MockUserUseCase_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserUseCase_GetUser_Call) Return(_a0 *domain.User, _a1 error) *MockUserUseCase_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUseCase_GetUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.User, error)) *MockUserUseCase_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, query
func (_m *MockUserUseCase) ListUsers(ctx context.Context, query auth.ListUsersQuery) (*auth.PaginatedUsers, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *auth.PaginatedUsers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.ListUsersQuery) (*auth.PaginatedUsers, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.ListUsersQuery) *auth.PaginatedUsers); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.PaginatedUsers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.ListUsersQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUseCase_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserUseCase_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query auth.ListUsersQuery
func (_e *MockUserUseCase_Expecter) ListUsers(ctx interface{}, query interface{}) *MockUserUseCase_ListUsers_Call {
	return &MockUserUseCase_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, query)}
}

func (_c *MockUserUseCase_ListUsers_Call) Run(run func(ctx context.Context, query auth.ListUsersQuery)) *MockUserUseCase_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.ListUsersQuery))
	})
	return _c
}

func (_c *MockUserUseCase_ListUsers_Call) Return(_a0 *auth.PaginatedUsers, _a1 error) *MockUserUseCase_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUseCase_ListUsers_Call) RunAndReturn(run func(context.Context, auth.ListUsersQuery) (*auth.PaginatedUsers, error)) *MockUserUseCase_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, cmd
func (_m *MockUserUseCase) UpdateUser(ctx context.Context, cmd auth.UpdateUserCommand) (*domain.User, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.UpdateUserCommand) (*domain.User, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.UpdateUserCommand) *domain.User); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.UpdateUserCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUseCase_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserUseCase_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd auth.UpdateUserCommand
func (_e *MockUserUseCase_Expecter) UpdateUser(ctx interface{}, cmd interface{}) *MockUserUseCase_UpdateUser_Call {
	return &MockUserUseCase_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, cmd)}
}

func (_c *MockUserUseCase_UpdateUser_Call) Run(run func(ctx context.Context, cmd auth.UpdateUserCommand)) *MockUserUseCase_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.UpdateUserCommand))
	})
	return _c
}

func (_c *MockUserUseCase_UpdateUser_Call) Return(_a0 *domain.User, _a1 error) *MockUserUseCase_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUseCase_UpdateUser_Call) RunAndReturn(run func(context.Context, auth.UpdateUserCommand) (*domain.User, error)) *MockUserUseCase_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserUseCase creates a new instance of MockUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUseCase {
	mock := &MockUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
