with-expecter: true
packages:
  flowforge/internal/domain:
    config:
      dir: "internal/domain/mocks"
      outpkg: "mocks"
    interfaces:
      AuditRepository:
  flowforge/internal/auth:
    config:
      dir: "internal/auth/mocks"
      outpkg: "mocks"
    interfaces:
      UserRepository:
      AuthUseCase:
      UserUseCase:
      JWTService:
      PasswordService:
      TokenBlacklist:
      SessionStore:
  flowforge/internal/tenant:
    config:
      dir: "internal/tenant/mocks"
      outpkg: "mocks"
    interfaces:
      TenantRepository:
      TenantUseCase:
  flowforge/internal/workflow:
    config:
      dir: "internal/workflow/mocks"
      outpkg: "mocks"
    interfaces:
      WorkflowRepository:
      VersionRepository:
      WorkflowUseCase:
