// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: events.proto

// Generic event-delivery contract for FlowForge's gRPC ingress/egress adapters
// (Phase 7, decision D-4). This is a working placeholder pending the real
// external system's actual proto spec; adapting field names is isolated to
// internal/platform/eventbus.

package eventspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventListener_DeliverEvent_FullMethodName = "/flowforge.events.v1.EventListener/DeliverEvent"
)

// EventListenerClient is the client API for EventListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventListenerClient interface {
	DeliverEvent(ctx context.Context, in *DeliverEventRequest, opts ...grpc.CallOption) (*DeliverEventResponse, error)
}

type eventListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventListenerClient(cc grpc.ClientConnInterface) EventListenerClient {
	return &eventListenerClient{cc}
}

func (c *eventListenerClient) DeliverEvent(ctx context.Context, in *DeliverEventRequest, opts ...grpc.CallOption) (*DeliverEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverEventResponse)
	err := c.cc.Invoke(ctx, EventListener_DeliverEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventListenerServer is the server API for EventListener service.
// All implementations must embed UnimplementedEventListenerServer
// for forward compatibility.
type EventListenerServer interface {
	DeliverEvent(context.Context, *DeliverEventRequest) (*DeliverEventResponse, error)
	mustEmbedUnimplementedEventListenerServer()
}

// UnimplementedEventListenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventListenerServer struct{}

func (UnimplementedEventListenerServer) DeliverEvent(context.Context, *DeliverEventRequest) (*DeliverEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverEvent not implemented")
}
func (UnimplementedEventListenerServer) mustEmbedUnimplementedEventListenerServer() {}
func (UnimplementedEventListenerServer) testEmbeddedByValue()                       {}

// UnsafeEventListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventListenerServer will
// result in compilation errors.
type UnsafeEventListenerServer interface {
	mustEmbedUnimplementedEventListenerServer()
}

func RegisterEventListenerServer(s grpc.ServiceRegistrar, srv EventListenerServer) {
	// If the following call panics, it indicates UnimplementedEventListenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventListener_ServiceDesc, srv)
}

func _EventListener_DeliverEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).DeliverEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventListener_DeliverEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).DeliverEvent(ctx, req.(*DeliverEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventListener_ServiceDesc is the grpc.ServiceDesc for EventListener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventListener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flowforge.events.v1.EventListener",
	HandlerType: (*EventListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverEvent",
			Handler:    _EventListener_DeliverEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "events.proto",
}
