// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: events.proto

// Generic event-delivery contract for FlowForge's gRPC ingress/egress adapters
// (Phase 7, decision D-4). This is a working placeholder pending the real
// external system's actual proto spec; adapting field names is isolated to
// internal/platform/eventbus.

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliverEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationKey string                 `protobuf:"bytes,1,opt,name=correlation_key,json=correlationKey,proto3" json:"correlation_key,omitempty"`
	PayloadJson    []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliverEventRequest) Reset() {
	*x = DeliverEventRequest{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverEventRequest) ProtoMessage() {}

func (x *DeliverEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverEventRequest.ProtoReflect.Descriptor instead.
func (*DeliverEventRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverEventRequest) GetCorrelationKey() string {
	if x != nil {
		return x.CorrelationKey
	}
	return ""
}

func (x *DeliverEventRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type DeliverEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // mirrors the HTTP path: always true, matching/no-match is internal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverEventResponse) Reset() {
	*x = DeliverEventResponse{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverEventResponse) ProtoMessage() {}

func (x *DeliverEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverEventResponse.ProtoReflect.Descriptor instead.
func (*DeliverEventResponse) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x13flowforge.events.v1\"a\n" +
	"\x13DeliverEventRequest\x12'\n" +
	"\x0fcorrelation_key\x18\x01 \x01(\tR\x0ecorrelationKey\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\"2\n" +
	"\x14DeliverEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2t\n" +
	"\rEventListener\x12c\n" +
	"\fDeliverEvent\x12(.flowforge.events.v1.DeliverEventRequest\x1a).flowforge.events.v1.DeliverEventResponseB/Z-flowforge/internal/platform/eventbus/eventspbb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_proto_goTypes = []any{
	(*DeliverEventRequest)(nil),  // 0: flowforge.events.v1.DeliverEventRequest
	(*DeliverEventResponse)(nil), // 1: flowforge.events.v1.DeliverEventResponse
}
var file_events_proto_depIdxs = []int32{
	0, // 0: flowforge.events.v1.EventListener.DeliverEvent:input_type -> flowforge.events.v1.DeliverEventRequest
	1, // 1: flowforge.events.v1.EventListener.DeliverEvent:output_type -> flowforge.events.v1.DeliverEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
